services:
  #!App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practica_3_nestjs
    ports:
      - 3800:3000
    environment:
      - PG_DB_NAME=${PG_DB_NAME}
      - PG_DB_USER=${PG_DB_USER}
      - PG_DB_PASSWORD=${PG_DB_PASSWORD}
      - PG_DB_PORT=5432
      - PG_HOST=postgres
      - NODE_ENV=production
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:prod
  #!postgres:
  postgres:
    image: postgres
    container_name: practica_3_postgres
    restart: always
    environment:
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
    ports:
      - ${PG_DB_PORT}:5432
    volumes:
      - ./volumen/postgres:/var/lib/postgresql/data
